stfalcon_tinymce:
  include_jquery: true
  tinymce_jquery: true
  selector: ".tinymce"
  language: "%locale%"
#  use_callback_tinymce_init: true
  tinymce_buttons:
    stfalcon: # Id of the first button
      title: "Stfalcon"
      image: "http://stfalcon.com/favicon.ico"
    hello_world: # Id of the second button
      title: "Google"
      image: "http://google.com/favicon.ico"
#      image: "asset[bundles/somebundle/images/icon.ico]"
  theme:
#    advanced:
#      plugins:
#        - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
#        - "searchreplace wordcount visualblocks visualchars code fullscreen"
#        - "insertdatetime media nonbreaking save table contextmenu directionality"
#        - "emoticons template paste textcolor"
#      toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
#      toolbar2: "print preview media | forecolor backcolor emoticons | stfalcon | example"
#      image_advtab: true
#      templates:
#        - {title: 'Test template 1', content: 'Test 1'}
#        - {title: 'Test template 2', content: 'Test 2'}
#      # BBCode tag compatible theme (see http://www.bbcode.org/reference.php)
#      bbcode:
#        plugins: ["bbcode, code, link, preview"]
#        menubar: false
#        toolbar1: "bold,italic,underline,undo,redo,link,unlink,removeformat,cleanup,code,preview"
#    advanced:
#      plugins:
#        - 'print preview fullpage paste importcss searchreplace autolink autosave save directionality code visualblocks visualchars fullscreen image link media template codesample table charmap hr pagebreak nonbreaking anchor toc insertdatetime advlist lists wordcount imagetools textpattern noneditable charmap emoticons'
#      toolbar: 'undo redo | bold italic underline strikethrough | fontselect fontsizeselect formatselect | alignleft aligncenter alignright alignjustify | outdent indent |  numlist bullist | forecolor backcolor removeformat | pagebreak | charmap emoticons | fullscreen  preview save print | insertfile image media template link anchor codesample | ltr rtl'
#      toolbar_sticky: true
#      menubar: 'file edit view insert format tools table help'
    simple:
      theme: "modern"
#      content_css: "asset[css/app.css]"
#      toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
#      toolbar2: "print preview media | forecolor backcolor emoticons | stfalcon | hello_world"
#      content_css: "asset[css/app.css]"



