#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#blog_list:
#  path: /job
#  controller: App\Controller\JobController::index
fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/security.xml"
#  prefix: /%locale%
  prefix: /{_locale}
#  defaults:
#    locale: '%locale%'
#  prefix:
#    en: ''
#    ru: '/ru'

