#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#blog_list:
#  path: /job
#  controller: App\Controller\JobController::index

gesdinet_jwt_refresh_token:
  path:       /api/token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh

fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/security.xml"
#  prefix: /%locale%
  prefix: /{_locale}
#  defaults:
#    locale: '%locale%'
#  prefix:
#    en: ''
#    ru: '/ru'

api_login_check:
  path: /api/login_check